### ISSUE TITLE
Problem Installing Addon

### ISSUE THREAD

**Issue by kiri1121** [mrachinskiy/jewelcraft#17]
This is my first time stumbling upon your addon. With the version 2.3.1, if I try to install the add-on I receive this message:
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable mod = _import_(module_name)
File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\jewelcraft-master\_init_.py", line 60, in <module> from . import (
File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\jewelcraft-master\ui.py", line 26, in <module> from .lib import asset
File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\jewelcraft-master\lib\asset.py", line 23, in <module> from math import tau, sin, cos
ImportError: cannot import name 'tau'

I installed the previous version, 2.2.1, without issues.

**Comment by mrachinskiy** [comment]
JewelCraft 2.3.1 does not support Blender 2.79. Please use [How to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.
