### ISSUE TITLE
jewelcraft 2.40 error 1

### ISSUE THREAD

**Issue by Spirou4D** [mrachinskiy/jewelcraft#23]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Patrinux\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons_contrib\jewelcraft\__init__.py", line 129, in <module>
    ops_asset.WM_OT_asset_add,
AttributeError: module 'jewelcraft.ops_asset' has no attribute 'WM_OT_asset_add'

**Comment by mrachinskiy** [comment]
The path to the addon suggests that you installed it manually by moving addon files to `addons_contrib` folder, and you probably did it wrong.
Please check [how to install guide](https://github.com/mrachinskiy/jewelcraft#how-to-install).

**Comment by Spirou4D** [comment]
Ha yes now B2.8 install only one folder: addons in app-data!
BUT in the past(I'm older) it was possible to use addons in the "addons" and/or "addons_contrib" folders in app_data! Weird...
